### ISSUE TITLE
Enhancing a `makefile`

### ISSUE THREAD

**Issue by paul-green-stone** [paul-green-stone/guard#1]
The usage of static libraries sounds great! Here goes the first one.

I've tested this on my machine (*macOS Mojave Version 10.14.6*) and it works well. Lack of access to other OSs makes it a bit harder to experiment with it outside my system. I need a "proper", more "standard" way of writing `makefile` that creates a static library

**Comment by BrickSigma** [comment]
Tested makefile on Linux and fixed small issues with variable names to meet GNU make conventions along with reordering of targets.
